name = "amabuid-backend"
compatibility_date = "2024-01-15"
main = "src/index.ts"

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"
